# -*- coding: utf-8 -*-
"""A1_DataLoad_Cartwheel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ugTQjYfyZa_KC-d1SXBO4jD9kCvAY8nB

# Undertanding the cartwheel data set

The notebook aims to undertand the content of the cartwheel data set.


## Acknowledgments

- Data from https://www.coursera.org/ from the course "Understanding and Visualizing Data with Python" by University of Michigan

# Cartwheel data set

1. A cartwheel

![cartwheel1.png](https://drive.google.com/uc?export=view&id=1h6CbMZX9wtRIbxpREgHSLY5IKTEqq6l6)

2. The dataset description
    - The dataset used here is an extension from the original cartwheel dataset from cursera
    - Total numer of observations: 52
    - Many observations/measurements/recordings of the characteristics/attributes/variables of cartwheel executions
    - Variables: Age, Gender, GenderGroup, Glasses, GlassesGroup, Height, Wingspan, CWDistance, ... (X variables)

# Importing and inspecting the data
"""

RunInColab = True     # (False: no  | True: yes)

# colab:
if RunInColab:
    # Mount your google drive in google colab
    from google.colab import drive
    drive.mount('/content/drive')

    # Define ruta del proyecto
    Ruta = "/content/drive/My Drive/Reto_Sistemas_Eléctricos/NotebooksProfessor/"

else:
    # Define path del proyecto
    Ruta = ""

# Import the packages that we will be using
import matplotlib.pyplot as plt
import pandas as pd

# Dataset url
url = Ruta + "datasets/cartwheel/cartwheel.csv"

# Load the dataset
dataset = pd.read_csv(url)

# Print the dataset
dataset

# Print the number of rows
Nrows = dataset.shape[0]
Nrows

# Print the number of columns
Ncols = dataset.shape[1]
Ncols

"""# Data types"""



"""# Activity: work with the iris dataset

1. Load the iris.csv file in your computer and understand the dataset


2. How many observations (rows) are in total?


3. How many variables (columns) are in total? What do they represent?


4. How many observations are for each type of flower?


5. What is the type of data for each variable?


6. What are the units of each variable?

2. Aparently there are 150 rows

3. The total columns are 5, each representing some kind of measurement except for the final, which appears to show the type of flower in question

4. There are a total of 50 observations for each type

5. For the 4 first columns, which are measurements the type of data is a float, a positive real number

6. The units for all variables except the type of flower is cm
"""

RunInColab = True     # (False: no  | True: yes)

# colab:
if RunInColab:
    # Mount your google drive in google colab
    from google.colab import drive
    drive.mount('/content/drive')

    # Define ruta del proyecto
    Ruta = "/content/drive/My Drive/Reto_Sistemas_Eléctricos/NotebooksProfessor/"

else:
    # Define ruta del proyecto
    Ruta = ""

# Import the packages that we will be using
import matplotlib.pyplot as plt
import pandas as pd

# Dataset url
url = Ruta + "datasets/iris/iris.csv"

# Load the dataset
colnames=['Measure 1','Measure 2','Measure 3','Measure 4','Type']
dataset = pd.read_csv(url, header=None, names=colnames)

# Print the dataset
dataset

# Print the number of rows
Nrows = dataset.shape[0]
Nrows

# Print the number of columns
Ncols = dataset.shape[1]
Ncols

conteo_flor = dataset['Type'].value_counts()

# Número de datos para cada tipo de flor
print("Datos de cada tipo de flor: ")
print(conteo_flor)