# -*- coding: utf-8 -*-
"""A2_DataManagment_Cartwheel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X6u5sHFgyxReMkGoigvdmLKYid2DzGyd

# Activity: work with the iris dataset

Repeat this tutorial with the iris data set and respond to the following inquiries

1. Calculate the statistical summary for each quantitative variables. Explain the results
    - Identify the name of each column
    - Identify the type of each column
    - Minimum, maximum, mean, average, median, standar deviation
    
    
2. Are there missing data? If so, create a new dataset containing only the rows with the non-missing data


3. Create a new dataset containing only the petal width and length and the type of Flower


4. Create a new dataset containing only the setal width and length and the type of Flower


5. Create a new dataset containing the setal width and length and the type of Flower encoded as a categorical numerical column
"""

RunInColab = True     # (False: no  | True: yes)

# colab:
if RunInColab:
    # Mount your google drive in google colab
    from google.colab import drive
    drive.mount('/content/drive')

    # Define ruta del proyecto
    Ruta = "/content/drive/My Drive/Reto_Sistemas_Eléctricos/NotebooksProfessor/"

else:
    # Define ruta del proyecto
    Ruta = ""

# Import the packages that we will be using
import matplotlib.pyplot as plt
import pandas as pd

# Dataset url
url = Ruta + "datasets/iris/iris.csv"

# Load the dataset
colnames=['Sepal length', 'Sepal width', 'Petal length', 'Petal width','Type']
dataset = pd.read_csv(url, header=None, names=colnames)

# Print the data
dataset

df.columns

df.dtypes

df.describe()

dataset2 = dataset.dropna()

# Mostrar los datos sin valores faltantes
print(dataset2)

dataset3 = dataset2[['Petal length', 'Petal width', 'Type']]
#Mostrar datos seleccionados
print(dataset3.head())

dataset3 = dataset2[['Sepal length', 'Sepal width', 'Type']]
#Mostrar datos seleccionados
print(dataset3.head())

Nrows = dataset3.shape[0]
Ncols = dataset3.shape[1]
print("Rows:",Nrows)
print("Columns:",Ncols)

# Crear un mapeo de tipo de flor a un número único
Cat_num = {'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}

# Crear una columna numérica categórica para el tipo de flor
dataset['Encoded_Type'] = dataset['Type'].map(Cat_num)

# Crear un nuevo conjunto de datos con el ancho y la longitud del sépalo y el tipo de flor codificado
dataset4 = dataset[['Sepal length', 'Sepal width', 'Encoded_Type']]

# Mostrar las primeras filas del nuevo conjunto de datos
print(dataset4.head())