# -*- coding: utf-8 -*-
"""A3_DataVisualization_Cartwheel_EMPTY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GzvdRhQDa-KR7JCkzdItujrnHy5jA126

# Activity: work with the iris dataset

Repeat this tutorial with the iris data set and respond to the following inquiries

1. Plot the histograms for each of the four quantitative variables


2. Plot the histograms for each of the quantitative variables


3. Plot the boxplots for each of the quantitative variables


4. Plot the boxplots of the petal width grouped by type of flower


5. Plot the boxplots of the setal length grouped by type of flower


6. Provide a description (explaination from your observations) of each of the quantitative variables
"""

RunInColab = True     # (False: no  | True: yes)
# colab:
if RunInColab:
    # Mount your google drive in google colab
    from google.colab import drive
    drive.mount('/content/drive')

    # Define ruta del proyecto
    Ruta = "/content/drive/My Drive/Reto_Sistemas_Eléctricos/NotebooksProfessor/"

else:
    # Define ruta del proyecto
    Ruta = ""
    # Import the packages that we will be using
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Dataset url
url = Ruta + "datasets/iris/iris.csv"

# Load the dataset
colnames=['Sepal length', 'Sepal width', 'Petal length', 'Petal width','Type']
df = pd.read_csv(url, header=None, names=colnames)

# Print the data
df

#Histogramas para cada una de las cuatro variables cuantitativas
#Sepal Length
sns.histplot(df['Sepal length'])
plt.show()

#Sepal Width
sns.histplot(df['Sepal width'])
plt.show()


#petal Width
sns.histplot(df['Petal width'])
plt.show()


#Petal Width
sns.histplot(df['Petal width'])
plt.show()